#include "dispatch.hpp"
#include <array>
#include <cstring>
#include <iostream>
#include <stdexcept>

// Test entries record which generated entry the recovered host selected.
// They never emulate or qualify device computation.
#define ENTRY(name, symbol) void name() asm(symbol); void name() {}
ENTRY(layout_f16, "_ZN6tecoep7kernels34__device_stub__get_dispatch_layoutIDF16_DF16_EEvPcmiiiiiiiiiiPiPT0_PT_S3_S3_")
ENTRY(layout_f32, "_ZN6tecoep7kernels34__device_stub__get_dispatch_layoutIDF16_fEEvPcmiiiiiiiiiiPiPT0_PT_S3_S3_")
ENTRY(layout_lowlatency_f16, "_ZN6tecoep7kernels45__device_stub__get_dispatch_layout_lowlatencyIDF16_DF16_EEvPcmiiiiiiiiiiPiPT0_PT_S3_S3_Pm")
ENTRY(layout_lowlatency_f32, "_ZN6tecoep7kernels45__device_stub__get_dispatch_layout_lowlatencyIDF16_fEEvPcmiiiiiiiiiiPiPT0_PT_S3_S3_Pm")
ENTRY(gather_f16, "_ZN6tecoep7kernels35__device_stub__gather_dispatch_dataIDF16_DF16_EEvPcS2_miiiiPiS3_PT0_PT_")
ENTRY(gather_f32, "_ZN6tecoep7kernels35__device_stub__gather_dispatch_dataIDF16_fEEvPcS2_miiiiPiS3_PT0_PT_")
ENTRY(gather_lowlatency_f16, "_ZN6tecoep7kernels46__device_stub__gather_dispatch_data_lowlatencyIDF16_DF16_EEvPcS2_miiiiPiS3_PT0_PT_Pm")
ENTRY(gather_lowlatency_f32, "_ZN6tecoep7kernels46__device_stub__gather_dispatch_data_lowlatencyIDF16_fEEvPcS2_miiiiPiS3_PT0_PT_Pm")
#undef ENTRY

namespace {
void require(bool value, const char* reason) {
    if (!value) throw std::runtime_error(reason);
}
void* ptr(std::uintptr_t value) { return reinterpret_cast<void*>(value); }
sdaaStream_t stream = reinterpret_cast<sdaaStream_t>(0x1234);
sdaaStream_t popped_stream = reinterpret_cast<sdaaStream_t>(0x5678);
int pushes = 0, pops = 0, launches = 0;
sdaaError_t push_result = sdaaSuccess;
sdaaError_t pop_result = sdaaSuccess;
sdaaError_t launch_result = sdaaSuccess;
const void* selected_entry = nullptr;
std::array<unsigned char, 104> payload{};
std::size_t payload_size = 0;

EP_DISPATCH layout(EP_DTYPE hidden, EP_DTYPE weight, int dp = 1, int ep = 5) {
    return tecoep::kernels::get_dispatch_layout(stream, ptr(0x11),
        0x9988776655443322UL, dp, 2, 3, 4, ep, 6, 7, 8, 9, 10,
        ptr(0x31), ptr(0x32), ptr(0x33), ptr(0x34), ptr(0x35), hidden, weight);
}
}

extern "C" sdaaError_t __sdaaPushCallConfiguration(std::size_t shared, sdaaStream_t s) {
    require(shared == 1 && s == stream, "original push configuration");
    ++pushes;
    return push_result;
}
extern "C" sdaaError_t __sdaaPopCallConfiguration(std::size_t* shared, sdaaStream_t* s) {
    ++pops;
    *shared = 7;
    *s = popped_stream;
    return pop_result;
}
extern "C" sdaaError_t sdaaLaunchKernel(const void* entry, void** args,
                                        std::size_t shared, sdaaStream_t s) {
    require(args[0] == ptr(1) && args[2] == ptr(2) && args[4] == nullptr,
            "original packed buffer descriptor");
    require(shared == 7 && s == popped_stream, "popped configuration forwarded");
    selected_entry = entry;
    payload_size = reinterpret_cast<std::uintptr_t>(args[3]);
    require(payload_size <= payload.size(), "bounded payload");
    std::memcpy(payload.data(), args[1], payload_size);
    ++launches;
    return launch_result;
}

int main() {
    // Expected words are independently transcribed from original host stores:
    // 0x2e4c..0x2ed8, rather than generated by the recovered argument structs.
    const std::uint64_t expected_layout[] = {
        0x11, 0x9988776655443322UL, 0x0000000200000001UL,
        0x0000000400000003UL, 0x0000000600000005UL,
        0x0000000800000007UL, 0x0000000a00000009UL,
        0x31, 0x32, 0x33, 0x34, 0x35,
    };
    for (int h = 0; h < 6; ++h) {
        for (int w = 0; w < 6; ++w) {
            const int before = launches;
            const bool supported = h == 0 && (w == 0 || w == 2);
            require(layout(static_cast<EP_DTYPE>(h), static_cast<EP_DTYPE>(w)) ==
                    (supported ? EP_RETURN_SUCCESS : EP_RETURN_FAILED), "dtype result");
            require(launches == before + supported, "dtype launch guard");
            if (supported) {
                require(selected_entry == reinterpret_cast<const void*>(w == 0 ? layout_f16 : layout_f32),
                        "layout coefficient entry");
                require(payload_size == 96 && !std::memcmp(payload.data(), expected_layout, 96),
                        "layout original pointer and scalar offsets");
            }
        }
    }
    require(layout(EP_DTYPE_FLOAT16, EP_DTYPE_FLOAT16, 32, 32) == EP_RETURN_SUCCESS, "32 limit");
    const int before = launches;
    require(layout(EP_DTYPE_FLOAT16, EP_DTYPE_FLOAT16, 33) == EP_RETURN_FAILED, "dp limit");
    require(layout(EP_DTYPE_FLOAT16, EP_DTYPE_FLOAT16, 1, 33) == EP_RETURN_FAILED, "ep limit");
    require(launches == before, "capacity guard does not launch");
    require(layout(EP_DTYPE_FLOAT16, EP_DTYPE_FLOAT16, -1, -1) == EP_RETURN_SUCCESS,
            "original signed upper bound");

    push_result = static_cast<sdaaError_t>(1);
    const int before_push_failure = launches, before_pop_failure = pops;
    require(layout(EP_DTYPE_FLOAT16, EP_DTYPE_FLOAT32) == EP_RETURN_FAILED,
            "push error is propagated");
    require(launches == before_push_failure && pops == before_pop_failure, "push error stops launch");
    push_result = sdaaSuccess;
    pop_result = static_cast<sdaaError_t>(1);
    require(layout(EP_DTYPE_FLOAT16, EP_DTYPE_FLOAT32) == EP_RETURN_FAILED,
            "pop error is propagated without launch");
    require(launches == before_push_failure, "pop failure does not launch");
    pop_result = sdaaSuccess;
    launch_result = static_cast<sdaaError_t>(1);
    require(layout(EP_DTYPE_FLOAT16, EP_DTYPE_FLOAT32) == EP_RETURN_FAILED,
            "launch error is propagated");
    launch_result = sdaaSuccess;

    auto* barrier = reinterpret_cast<unsigned long*>(0x55);
    tecoep::kernels::get_dispatch_layout_lowlatency(stream, ptr(0x11),
        0x9988776655443322UL, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
        ptr(0x31), ptr(0x32), ptr(0x33), ptr(0x34), ptr(0x35),
        EP_DTYPE_FLOAT16, EP_DTYPE_FLOAT32, barrier);
    require(selected_entry == reinterpret_cast<const void*>(layout_lowlatency_f32) &&
            payload_size == 104 && !std::memcmp(payload.data(), expected_layout, 96), "low latency layout");
    std::uint64_t tail;
    std::memcpy(&tail, payload.data() + 96, 8);
    require(tail == 0x55, "layout barrier pointer");

    // Gather has no host dp_size <= 32 guard; dp_size=33 must reach the entry.
    const std::uint64_t expected_gather[] = {
        0x11, 0x22, 0x9988776655443322UL, 0x0000002100000011UL,
        0x0000140000000008UL, 0x31, 0x32, 0x33, 0x34,
    };
    for (auto weight : {EP_DTYPE_FLOAT16, EP_DTYPE_FLOAT32}) {
        tecoep::kernels::gather_dispatch_data(stream, ptr(0x11), ptr(0x22),
            0x9988776655443322UL, 17, 33, 8, 5120, ptr(0x31), ptr(0x32),
            ptr(0x33), ptr(0x34), EP_DTYPE_FLOAT16, weight);
        require(selected_entry == reinterpret_cast<const void*>(weight == EP_DTYPE_FLOAT16 ? gather_f16 : gather_f32),
                "gather coefficient entry");
        require(payload_size == 72 && !std::memcmp(payload.data(), expected_gather, 72), "gather offsets");
        tecoep::kernels::gather_dispatch_data_lowlatency(stream, ptr(0x11), ptr(0x22),
            0x9988776655443322UL, 17, 33, 8, 5120, ptr(0x31), ptr(0x32),
            ptr(0x33), ptr(0x34), EP_DTYPE_FLOAT16, weight, barrier);
        require(selected_entry == reinterpret_cast<const void*>(weight == EP_DTYPE_FLOAT16 ?
                    gather_lowlatency_f16 : gather_lowlatency_f32), "low latency gather entry");
        require(payload_size == 80 && !std::memcmp(payload.data(), expected_gather, 72), "low latency gather");
        std::memcpy(&tail, payload.data() + 72, 8);
        require(tail == 0x55, "gather barrier pointer");
    }
    require(pushes == pops + 1 && pops == launches + 1, "configuration call sequence");
    std::cout << "Recovered host dispatch contracts passed; device computation is untested.\n";
}
